2024-Winter-Bootcamp-Team-G/frontend

src/App.jsx
src/components/Background.jsx
src/components/Button.jsx
src/components/Window.jsx

<br>
<br>
close #8 
<br>
<br>
- 윈도우 창 반응형이랑 x버튼 Button.jsx 사용하도록 수정
- Background.jsx 언더바 반응형 되도록 수정
- Button.jsx 인수로 위치 값 받을 수 있도록 수정
- <br>
<br>

refactor: 반응형 수정

---

src/components/Background.jsx
src/components/Button.jsx
src/components/Input.jsx
src/components/Window.jsx

<br>
<br>
close #17
<br>
<br>
- <br>
- <br>
<br>

반응형 수정하려고 노력함

---

src/App.jsx
src/assets/triangle.svg
src/components/Mbutton.jsx
src/components/Window2.jsx
src/pages/MiniH.jsx
src/pages/TestPage.jsx

<br>
이부분 날짜추가하였습니다.
<br>
close #15 
<br>
<br>
- <br>
- <br>
<br>

design: 미니홈피 버튼 및 날짜 추가

---

src/assets/page.svg
src/components/Mbutton.jsx
src/components/MiniHomp.jsx
src/pages/MiniH.jsx

<br>
<br>
close #20
<br> 날짜는 흠 먼가 TODAY 2025 | 250116 은 좀 이상한 거 같아서 날짜만 넣어 봤구여 별로면 다시 바꺼도 댐 ㅋ
<br>
- <br>
- <br>
<br>

design: 미니홈피 레이아웃 반응형

---

src/components/MiniHomp.jsx
src/components/Mpopup.jsx

<br>
<br>
close #27
<br>
<br>
- <br>
- <br> x나 닫기 버튼 누르면 팝업창 닫기도 추가
<br>

feat: 버튼&팝업창 연결

---

src/App.jsx
src/components/MiniHomp.jsx
src/pages/Board.jsx
src/pages/MiniH.jsx
src/pages/Notice.jsx

<br>
<br>
close #35
<br>
<br>
- <br>
- <br>
<br>

design: 디테일 수정

---

package.json
src/components/Window2.jsx
src/pages/Board.jsx
src/pages/MiniH.jsx
src/pages/Start.jsx
tailwind.config.js
yarn.lock

<br>
<br>
close #43
<br>
<br>
- 글씨 크기 살짝 조정
- 홈 화면 스크롤바 숨김
- ai 이미지 넣은 칸 크기 수정
- 시작하기 화면을 만들긴 했는데 아이콘이랑 제목 정해지면 사진 수정 해야함!
- 홈화면에 5번도 작성했음.. 근데 스크롤 내려서 안볼 거 같으면 위쪽에 5번까지 있다고 적어둬도 좋을 듯!!
<br>

design: 스크롤바 숨김&이미지 비율 조정

---

package.json
src/components/RadarChartComponent.jsx
src/pages/Share.jsx
yarn.lock

<br>
<br>
호버 기능도 추가하였음
close #45 
<br>
<br>
- <br>
- <br>
<br>

design: radar 차트 구현

---

src/components/Background.jsx
src/components/VennDiagram.jsx
src/pages/Share.jsx

<br>
close #48
<br>
<br>
- 벤다이어그램 생성
- <br>
<br>

design: 벤다이어그램 생성

---

src/components/VennDiagram.jsx
src/pages/Board.jsx

<br>
<br>
close #50
<br>
<br>
- <br>
- ai 이미지 크기 조정!!!!! 진짜진짜 마지막!!!!!!!!!!!!
<br>

design: 벤다이어그램 툴팁 추가

---

package.json
src/App.jsx
src/pages/Login.jsx
vite.config.js
yarn.lock

<br>
<br>
close #55
<br>
<br>
- <br>
- <br>
<br>

feat: 로그인 API 연동

---

src/pages/Login.jsx

<br>
<br>
close #57
<br>
<br>
기존의 Form data에서 json 형식으로 바꾸었습니다.
- <br>
- <br>
<br>

feat: 로그인 연동 수정

---

.gitignore
package.json
src/utils/cookie.js
yarn.lock

<br>
<br>
close #60
<br>
<br>
- <br>
- <br>
<br>

chore: cookie.js 정의

---

.gitignore
package.json
src/components/Background.jsx
src/pages/Login.jsx
yarn.lock

<br>
<br>
close #57
<br>
로그아웃, 로그인 cookie 추가 및 연동
- <br>
- <br>
<br>

Feat/#57 로그아웃 연동

---

src/components/Mpopup.jsx

<br>
<br>
close #59 
<br>
<br>
- <br> google oauth 인증 요청 추가
- <br>
<br>

feat: google oauth 인증 요청 추가

---

src/api/axios_config.js
src/utils/cookie.js

<br>
<br>
close #64
<br>
<br>
- <br>
- <br>
<br>

feat: axios_config 생성

---

src/components/Background.jsx
src/pages/Login.jsx

<br>
<br>
close #67
<br>
<br>
login, background -> axios_config와 연결!!함!
- <br>
- <br>
<br>

feat: 로그인, 로그아웃 api 연동 수정

---

src/pages/SignUp.jsx

<br>
<br>
close #69
<br>
회원가입 페이지 custom axios 사용해서 리팩토링!!!!
- <br>
- <br>
<br>

refactor: 회원가입 페이지 리팩토링

---

src/components/MiniHomp.jsx
src/pages/Board.jsx
src/pages/Login.jsx

<br>
<br>
close #76
<br>
<br>
보드판 완료하기 버튼에 연동되어있어서 완료하기 누르면 보드 생성됩니다. 임시임
- <br>
- <br>
<br>

feat:(임시)보드 생성하기 연동

---

src/api/axios_config.js
src/components/MiniHomp.jsx
src/components/Mpopup.jsx
src/pages/Board.jsx

<br>
<br>
close #72
<br>
<br>
- <br>
- <br>
<br>

feat: 보드 공유하기 api 구현

---

src/components/MiniHomp.jsx
src/pages/Board.jsx
src/pages/MiniH.jsx
src/pages/Notice.jsx

<br>
<br>
close #80
<br>
<br>
- 아직 글 누르면 그 보드판으로 이동하는 건 구현 못해뜸 ㅜ
- <br>
<br>

feat: 게시판 구현

---

src/components/MiniHomp.jsx
src/components/Mpopup.jsx
src/pages/MiniH.jsx

<br>
<br>
close #78
<br>
<br>
- <br>
- <br>
<br>

feat: 닉네임과 정보수정 연동

---

src/components/Mpopup.jsx

<br>
<br>
close #83
<br>
<br>
- <br>
- <br>
<br>

refactor: 정보수정창 수정

---

src/App.jsx
src/api/board.js
src/components/MiniHomp.jsx
src/components/Mpopup.jsx
src/pages/Board.jsx
src/pages/Notice.jsx

<br>
<br>
close #86
<br>
<br>
- <br>
- <br>
<br>

refactor: 재생성 이미지 버튼 바꿈/ custom api 추가

---

src/components/MiniHomp.jsx
src/components/Mpopup.jsx
src/components/RadarChartComponent.jsx
src/components/Select.jsx
src/components/VennDiagram.jsx
src/pages/Share.jsx

<br>
<br>
close #88
<br>
<br>
추후에 카테고리 이름 업데이트 시 수정할 예정.
보드 선택창도 바꿨어요
- <br>
- <br>
<br>

feat: 알고리즘 일치율 차트 연동 및 선택창 수정

---

src/components/MiniHomp.jsx
src/components/Mpopup.jsx
src/pages/Board.jsx
src/pages/Notice.jsx
src/utils/cookie.js

<br>
<br>
close #89
<br>
<br>
- <br>
- <br>
<br>

feat: 구독 채널 선택 & 보드판 생성 & 게시판 글 누르면 해당 보드판으로 이동 

---

src/components/Match.jsx
src/components/Mpopup.jsx
src/pages/Share.jsx

<br>
<br>
close #95
<br>
<br>
유효코드 입력창 수정 및 board_uuid와 연동 완료 알고리즘 일치율 보드판 수정 예정.. 이상한것같어서.. 
- <br>
- <br>
<br>

feat: 유효코드 공유하기 창 연동하기

---

src/components/RadarChartComponent.jsx
src/pages/Share.jsx

<br>
<br>
close #113
<br>
<br>
- <br>
- <br>
<br>

Refactor:일치율 보드판 찐 최종!!

---

src/components/Mbutton.jsx
src/components/MiniHomp.jsx
src/pages/Board.jsx

<br>
<br>
close #114
<br>
<br>
- <br>
- <br>
<br>

design: 디자인 수정

---

vercel.json

<br>
vercel.json 설정
<br>
close #122 
<br>
<br>
- <br>
- <br>
<br>

[feat] vercel.json 설정

---

src/components/Background.jsx
src/components/MiniHomp.jsx
src/pages/MiniH.jsx
src/pages/SignUp.jsx

<br>
<br>
close #131
<br>
<br>
- <br>
- <br>
<br>

design: 팝업창 내용 수정
